### ISSUE TITLE
(IOS)Component 'RNRectangleScanner' re-registered direct event 'topPictureTaken' as a bubbling event

### ISSUE THREAD

**Issue by jenyagalushka** [HarvestProfit/react-native-rectangle-scanner#30]
I got this problem after installing the library
![IMG_0029](https://user-images.githubusercontent.com/37962306/75988224-e6c8ac00-5ef9-11ea-9c3a-e0ec5c3868cb.PNG)

**Comment by humphreyja** [comment]
@jenyagalushka Is this on a new install? There isn't an event with that name used anywhere in this package. Maybe you have an existing or old package that is conflicting with this package?

**Comment by ahmetozalp** [comment]
https://github.com/HarvestProfit/react-native-rectangle-scanner/pull/31


Fix.

**Comment by humphreyja** [comment]
#31 should have fixed this. Please update to at least version 1.0.9

**Comment by jenyagalushka** [comment]
@humphreyja @ahmetozalp thank you so much!

**Comment by brennansaul** [comment]
I had this same issue and I believe that it was because i was previously using a different scanning module. I resolved the issue with the following steps:

- Removed the old file from package.json
- Deleted package-lock.json
- Deleted `node_modules` folder
- Deleted `Podfile.lock`
- Deleted `Pods` folder
- Reinstalled node modules with `npm install`
- Reinstalled pods with `cd ios && pod install && cd ..`
- Restarted app with `npm run ios`
