### ISSUE TITLE
Option to use the initial image to crop on?

### ISSUE THREAD

**Issue by breeeeeze** [HarvestProfit/react-native-rectangle-scanner#41]
Is there a way to call the scanner on the initial image instead of the camera? I was trying to give the option to crop again on the initial photo manually.

**Comment by humphreyja** [comment]
@breeeeeze Do you mean that you want to give the package an image to find a rectangle and crop to that, rather than using the camera? 

I don't have anything like that yet. I have been thinking of exposing an API that would allow you to do that.  Something like `camera.detectRectangleInImage(image)` and `camera.cropImageToRectangle(rectangleCoords)`. But this is not something I had planned to add in the near future.

**Comment by breeeeeze** [comment]
That sounds great, I'll see what I can find as well and will update this later

**Comment by mpkelly** [comment]
This would be nice. Live scan is quite jumpy so a static image as he input would be useful.
