### ISSUE TITLE
Speed up the automatic photo

### ISSUE THREAD

**Issue by cagv24** [HarvestProfit/react-native-rectangle-scanner#43]
Hi @humphreyja, I would like to change the speed of the automatic photo. Could you please tell me what is the algorithm that does this?

**Comment by humphreyja** [comment]
So this is done mostly in javascript actually, in the Rectangle Overlay. https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/src/RectangleOverlay.js#L80
It has props that allow you to change how many frames to wait before auto capture. 

Something that we could do is increase the detection rate on the iOS and Android side as well.

On Android, this is handled [here](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/views/RectangleDetectionController.java#L123). I set a delay on sending the message to the image processor. This could just be removed honestly. I didn't want the background process doing too much work to support older phones. Also, it gives a chance for the capture message to jump to the front of the queue on capture. But again, I think this could be changed.

On iOS, this is just a simple integer value that can be changed [here](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/ios/RectangleDetectionController.m#L71). This just toggles a flag that only allows processing a rectangle every 20 milliseconds. Again, so that it doesn't overwhelm the processor. (Though I'm not 100% certain as to if this is best practice, unnecessary, or an excessive amount).

Hope this helps!

**Comment by cagv24** [comment]
I think modifying the passed props to the Rectangle Overlay is enough. Thank you so much.
