### ISSUE TITLE
Unable to access cached Images when testing on device

### ISSUE THREAD

**Issue by shandilya1998** [HarvestProfit/react-native-rectangle-scanner#61]
When I am testing the app on an iPhone, the component caches the image, but when i try to access it in another component, I am unable to access the image. The component saves the image to this location
[/var/mobile/Containers/Data/Application/59EAEB13-CE87-403F-A10D-179A9AA44A8A/Library/Caches/RNRectangleScanner/C1595086068.jpeg]
But when i pass this location uri to an Image component to display, the Image is not found. Moreover, there is no such folder as in /var.mobile on my mac. The onPictureTaken and onPictureProcessed callbacks are called perfectly, and I also get back uri. But the URIs seem to be invalid. My metro bundler is running within a docker container, which also does not have this folder. Can someone explain how the images are actually cached? I am decent at js but not so good with either obj C or java. I will perform the same tests on an android phone and tell if the results are the same.

**Comment by humphreyja** [comment]
You could check if the file is being saved to `~/Library/Developer/CoreSimulator/Devices/:deviceID:/data/tmp`.  I believe this is where simulator cache data is stored and it is just symlinked to that directory. The given path should work though. Maybe docker is the issue here. I don't have much experience with running it in a docker container and how that may mess with the iOS simulator. 

To help, here is some info from the codebase.

I retrieve the cache folder using standard iOS practices, with `NSCachesDirectory`. 
I then ensure a `RNRectangeScanner` folder is created in that caches directory. (This is so you can use something like `RNFetchBlob.fs.unlink('${RNFetchBlob.fs.dirs.CacheDir}/RNRectangleScanner/')` to clear the cache to clean up the app. iOS does this sometimes like after an update but you may want to clear this manually if you are using lots of images. I think iOS may cap your cache folder size allowance as well so this is another reason to do that.).

I then save the files as `O:timestamp:.jpeg` and `C:timestamp:.jpeg` in that folder. Each operation is wrapped in a condition checking for failure, so the `onErrorProcessingImage ` will fire in the event of a failed storage operation.

Let me know if that helps!

**Comment by shandilya1998** [comment]
Turns out i can read the image if i use `react-native-fs` to read the image. The image gets stored onto the file system of the **device and is not accessible to the metro bundler** as the path is that of the device and not the system on which the metro bundler is running. I am not sure why this is happening. I don't really have native iOS experience, but what i understand, using the cache folder obtained using `NSCachesDirectory `gives the **cache directory folder path on the device and this path is not accessible to the metro bundler being on the device and not on the system** for some reasons on iOS. I am running the same code on android to see if the behaviour is the same on android as well.

**Comment by shandilya1998** [comment]
Same thing can

**Comment by humphreyja** [comment]
So that assessment is correct. That is why `react-native-fs` exists. It uses native code to perform CRUD operations on the file system. Using Javascript/nodejs does not work because nodejs does not run on the system. (i.e. metro does not run on the system). Metro runs a server on your computer which builds the javascript, which is then executed on a javascript UI thread on the device. Basically this means that like a browser, certain nodejs functions do not work. You cannot access the file system directly through javascript, the same way you can't access the camera directly though javascript. You need to use a bridge to interact with native functions to access these features. That's what `react-native-fs` does, the same way that this package gives your Javascript access to the camera!

Hope this helps!
